# Generated by Django 5.2.3 on 2025-07-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_userfiles_file_size_filedownloadtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSummaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='account_management.userfiles')),
            ],
        ),
    ]
